[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flower"
version = "1.0.0"
description = "Federated Learning for Latent ODEs"
license = "Apache-2.0"


[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "luisas"

[tool.flwr.app.components]
serverapp = "flower.server_app:app"
clientapp = "flower.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 2
fraction-fit = 1
fraction-evaluate = 1
local-epochs = 2
server-device = "cpu"
use-wandb = true
batch-size = 50
learning-rate = 0.1

[tool.flwr.federations]
default = "local-sim"

[tool.flwr.federations.local-sim]
options.num-supernodes = 2
options.backend.client-resources.num-cpus = 2 # each ClientApp assumes to use 2CPUs
options.backend.client-resources.num-gpus = 0.0 # ratio of VRAM a ClientApp has access to

[tool.flwr.federations.local-sim-gpu]
options.num-supernodes = 50
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 0.25